### ISSUE TITLE
StagingFailed error for pushing .net application windows stack

### ISSUE THREAD

**Issue by rahul221191** [cloudfoundry/loggregator#222]
CloudFoundary version-250
diego/1.4.1
windows windows2012R2
Cloud- aws
windows cell size-r3.xlarge

Hi i am trying to push a .net application on windows stack.But after starting the application its giving staging failed error.

We did RDP on window cell we are able to see some error in event viewer.

{"timestamp":1488899836.165504456,"process_id":4852,"source":"metron","log_level":"warn","message":"Failed to connect to etcd. Number of tries: 1. Backing off for 932Âµs.","data":{"error":"sync cluster failed"},"file":"C:/diego-windows-release/loggregator/src/metron/backoff/backoff.go","line":33,"method":"metron/backoff.Connect"

Can you please assist us with the problem?
Thanks in Advance

**Comment by apoydence** [comment]
@rahul221191 Normally `sync cluster failed` would imply that the etcd cluster is unhealthy (e.g. experiencing split brain). Therefore, I would recommend you take a look at the [failure recovery](https://github.com/cloudfoundry-incubator/etcd-release#failed-deploys-upgrades-split-brain-scenarios-etc) section in the etcd-release docs. After repairing etcd, please try restarting the metron agent.

**Comment by cfmagnum** [comment]
@apoydence Yes i tried the following command 

monit stop etcd (on all nodes in etcd cluster)
rm -rf /var/vcap/store/etcd/* (on all nodes in etcd cluster)
monit start etcd (one-by-one on each node in etcd cluster)

but still getting the same issue i.e staging failed error for winfdow app.

**Comment by ahevenor** [comment]
@cfmagnum sorry for the delay. The issues with etcd affect Loggregator but is probably not something we have direct control of. 

@dsabeti - any ideas what could be going wrong here?

**Comment by dsabeti** [comment]
A few thoughts:
1. Sometimes you get the `sync cluster failed` when etcd is working but clients are misconfigured. Is the etcd cluster using TLS to communicate with clients? Is the client (in this case, metron) configured with the correct certs and keys?
1. Etcd problems from metron can be misleading, because metron doesn't actually fail if etcd is inaccessible, it just logs the failure and performs the backoff. (This strategy is necessary because metron jobs colocated on consul VMs need to come before the etcd cluster is actually available.)

Let's collect a little more information:
1. What is the actual output from the CLI during the failed attempt to stage the app?
1. Run `CF_TRACE=true cf push` to find the request guid. You can use that to search logs a bit more effectively.
1. Look for logs in the CC Bridge. That's where most of the staging logic lives, even though it's ultimately performed on the cell. (Essentially, the stager creates a list of actions that the cell should do in order to stage the application.)

**Comment by ahevenor** [comment]
@rahul221191 Did your issue get solved? If so I'd like to close this issue.

**Comment by ahevenor** [comment]
Closing.
