### ISSUE TITLE
v1 doppler ingress does not increment `doppler.ingress` metric

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/loggregator#323]
[This](https://github.com/cloudfoundry/loggregator/blob/9d4239e5b430631e390973d15984979cc6e8313b/src/code.cloudfoundry.org/loggregator/doppler/internal/grpcmanager/v2/ingress_server.go#L83-L85) should be emitted [here](https://github.com/cloudfoundry/loggregator/blob/9d4239e5b430631e390973d15984979cc6e8313b/src/code.cloudfoundry.org/loggregator/doppler/internal/grpcmanager/v1/ingestor_server.go#L82).

**Comment by bradylove** [comment]
If we add this metric to the V1 ingress on doppler, I think it is important that we add a tag to the new and [existing counter](https://github.com/cloudfoundry/loggregator/blob/9d4239e5b430631e390973d15984979cc6e8313b/src/code.cloudfoundry.org/loggregator/doppler/internal/grpcmanager/v2/ingress_server.go#L47-L49) so that the API version is identifiable via the metric.

**Comment by jasonkeene** [comment]
@ahevenor said not to do this.

> I'd prefer not to emit `loggregator.doppler.ingress` for v1. that was what I thought we were doing originally.
