### ISSUE TITLE
renaming repo to doppler?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/loggregator#37]
I'm prob not only person confused by the renaming of loggregator to doppler. Is "loggregator" a thing still and "doppler" is something else?

Should this repo be renamed? Is the traffic controller now "doppler traffic controller"? Are all instances of "loggregator" (e.g. in the diagrams) now "doppler"? Or is there still a "loggregator" concept?

Github search for "cloudfoundry doppler" returns nothing; which didn't help me figure out the new differences :)

**Comment by ajackson** [comment]
So far we've been using the term "loggregator" to refer to the logging and metrics system as a whole (metron, doppler, and traffic controller).    We use the other terms to name each component or service within the infrastructure.   

There was some confusion since the bosh job name for the doppler component is still loggregator.   We want to fix this by changing the bosh job name to doppler.     

Does this make sense?   How can we better clarify both the system name and the component names?

**Comment by drnic** [comment]
I think that helps.

Would it hurt to call the whole thing "doppler" now; rename project; etc? Is the distinction helpful?

Perhaps the `doppler` subcomponent renamed to `doppler_server` and `loggregator_trafficcontroller` to `doppler_trafficcontroller`?

I'm asking on behalf of a friend, "future me", who might forget we had this conversation :D

**Comment by jmtuley** [comment]
I think we want to leave the names as they currently are:

* Loggregator is the entire log and metrics system
* Doppler is one component in the Loggregator system (that does some aggregation and filtering)
* Loggregator TrafficController is another component within the Loggregator system (acting as the external API server for the system)

I'd rather not change the name to `doppler_trafficcontroller`, because the current, more-general name gives us freedom to have it "control traffic" to more than just doppler, in case we ever add additional components interior to the Loggregator system.
