### ISSUE TITLE
Include org/space/name information with each log event

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry/loggregator#48]
As part of the CloudFoundry -> Logsearch integration I'm working on - https://github.com/logsearch/logsearch-for-cloudfoundry/pull/21 - I'd like to Log Analysis dashboards that include human readable names for log events.

Doppler tags all logs with a unique `cf_app_id` UUID, eg:

```
{"cf_app_id":"afc7d161-b5d5-44f2-a2c8-63870ff8f2db","level":"info","message_type":"OUT","msg":"goexample.apps.54.183.203.97.xip.io - [01/04/2015:10:22:50 +0000] \"GET / HTTP/1.1\" 200 7 \"-\" \"Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)\" 10.10.2.6:60637 x_forwarded_for:\"46.165.195.139, 10.10.2.6\" vcap_request_id:9f598459-f756-4ea4-58e5-e9f212ff328f response_time:0.002463550 app_id:afc7d161-b5d5-44f2-a2c8-63870ff8f2db\n","source_instance":"0","source_type":"RTR","time":"2015-04-01T10:22:50Z"}
```

UUID however, make for crappy dashboards:

![screen shot 2015-04-01 at 10 51 51](https://cloud.githubusercontent.com/assets/227505/6939213/36859e20-d862-11e4-977e-a03d3d58259b.png)

Are there any plans to include additional information in addition to the `cf_app_id` with each doppler firehost log event; specifically:

* `cf_app_name`
* `cf_space_id` and `cf_space_name`
* `cf_org_id` and `cf_org_name`

Thanks!

**Comment by drnic** [comment]
Oh yes please

**Comment by ajackson** [comment]
We've had [this discussion](https://groups.google.com/a/cloudfoundry.org/forum/#!searchin/vcap-dev/application$20name$20loggregator/vcap-dev/ccQoi6nNS4M/tJUCCtuU6TUJ) before on the mailing list.    It's important to note that application names aren't unique.    It is also possible to change the name of the app or reuse the same name for an app.   Loggregator also is not the source of truth for the appID to app name mapping, cloud controller is.   This means that loggregator would have to be given this info on a regular basis.   We don't want to couple loggregator to the CC any more that it already is, so having loggregator look it up at runtime seems like a bad idea.  We need a proposed solution that would be accurate, not confusing, avoids loggregator to CC coupling and has minimal runtime impact on the message flow through loggregator. Any ideas?  

So currently the best bet is to either allow users to annotate appIds with friendly names or build that mapping by looking up the appId in the Cloud Controller api.   (ideally on some interval to get changes)

**Comment by mrdavidlaing** [comment]
@ajackson; thanks for the thoughtful response; and the reminder of the discussion that has been had.  

I agree with @jbayer and @BrianMMcClain that the accuracy of the names isn't that big a deal; app names change infrequently and duplicate org/space/name combos in a "private CF" scenario will be rare.

However, I appreciate your point that the information lives in the Cloud Controller, so any solution is going to increase the coupling between Loggregator & CC.  Its a tough problem!

2 questions:
0.  Does Loggregator have any knowledge of the app's SpaceId and OrgId?  Or does it just know the AppId for each log stream?
0.  Could you expand on your idea to `allow users to annotate appIds with friendly names`.  Where are you thinking that the users would do this?  As part of the syslog service?  As an ENV variable in the app?

**Comment by mrdavidlaing** [comment]
@ajackson,

An apps `ENV:VCAP_APPLICATION`=
```json
{
 ...snip...
  "application_version": "61bd6b60-cbe7-4f8d-a197-57dfde3e9974",
  "application_name": "cf-env",
  "application_uris": [
    "cf-env.apps.54.183.203.97.xip.io"
  ],
  "version": "61bd6b60-cbe7-4f8d-a197-57dfde3e9974",
  "name": "cf-env",
  "space_name": "test",
  "space_id": "b1aa14ec-eaae-4e2c-804d-08b2ae75a2bf",
  "uris": [
    "cf-env.apps.54.183.203.97.xip.io"
  ],
  "users": null,
  "application_id": "abfc9a95-d20c-44bb-9771-4aba27856843",
 ...snip...
}
```

Would it be possible for loggregator to "reach into the app" and pluck out the `application_name`, `space_name` and `space_id`?

If so, this would give us a way to get most of the information desired, without increasing coupling on the Cloud Controller.

Thoughts?

**Comment by ajackson** [comment]
"Reaching into the app" isn't as simple as it sounds and breaks a lot of
boundaries in the system today.   This also involves more than just the
loggregator components.  From loggregator's perspective is that we can add
the additional data fields for org and space.  (names and ids).   Provided
we don't blow up our message size (more on that below). We'll have to get
other teams to weigh in on how easily those fields can actually be
populated. Loggregator takes a more passive approach and just transports
the data it's given; rather than trying to fill in, interpret or expand the
data.

Since loggregator isn't the source of truth for this data, it doesn't know
when the mapping between friendly names to ids change.  It would be up to
downstream systems to reconcile any changes.  It wouldn't be ideal if
downstream system's relied on names as the unique primary identifier for
apps, orgs, and spaces.  I fear that by having the "name" fields in the
message we are setting an expectation with downstream systems that we can't
actually deliver. My gut says that this would violate the principle of
least astonishment for downstream developers.  We could deliver one message
with id: 1234 name: foo and then next message with id: 1234 name: bar.  Or
worse have one app with { space_id : 1234 name : 'foo' } and another app
with { space_id : 1234 name : 'bar' }.  This could happen if the space
friendly name was changed between when app1 and app2 were started.  See cf
rename-space and cf rename-org commands on how to do this; also note that
cf rename will rename the application itself.  If I were on the receiving
end of this data I would be confused.  This is one large reason we didn't
include the names in the original design of the messages.  They simply
can't be trusted to not change.

A final minor concern for adding all these fields is that it will bloat
every message.  We should do some testing to figure out the impact of this
and exactly how much larger the messages would get.  Currently we are using
UDP for some of loggregator's internal communication and we like to keep
the message size below the MTU to prevent fragmentation.

I would propose that we don't add the names for applications, orgs or
spaces.   This would require downstream systems to lookup these values for
"friendly" display.  This could be done at presentation time by using the
cloud controller's API [0] or by building a local cache from the cloud
controller at regular intervals.  We could explore adding IDs for orgs and
spaces to the message. However since the appId is unique and applications
can't move between orgs and spaces the app ID should be sufficient.  If CF
every supports moving applications between spaces and/or orgs we also not
want these values in the message as they could also be incorrect for the
same reasons as the "name" fields above.  The best bet is to lookup the
current correct information for an application from the cloud controller.

This does put more of a burden on downstream systems need the org and space
information and/or friendly names. However it does prevent these systems
from having incorrect information.   If a downstream system didn't care
about the incorrectness due to a belief that in practice this information
will change infrequently for their particular CF deployment; I suggest they
expand the loggregator messages by annotating them with this additional
data from the Cloud Controller at ingest time.   I don't think this is a
safe assumption but I also understand that CF is being used in many
different domains.

By only sticking to information we can know is correct in the loggregator
message it keeps the core of CF consistent and doesn't prevent others from
solving their use case at the edge of the system.

[0] http://apidocs.cloudfoundry.org/205/apps/get_app_summary.html

**Comment by mrdavidlaing** [comment]
@ajackson, Thanks again for your considered response.

Given these technical limitations of loggregator, it doesn't seem feasible that additional app/space/name details can be added here.  I'll investigate alternative options for decorating log messages with additional information.
