### ISSUE TITLE
Stream endpoint: throttling

### ISSUE THREAD

**Issue by samu** [cloudfoundry/loggregator#57]
An app which generates massive amounts of logs can cause problems for the client who streams these logs via websocket. Current state of web technology does not foresee a throttling option for the `onmessage` event handler on a websocket connection, which means that a client using it will be exposed to an eventually overwhelming amount of events, leading to performance problems. The only option right now to solve this would be to cancel the connection.

Therefor it would be useful to have a throttling option on the `/stream` endpoint which allows to specify a maximum interval at which messages are sent. This would mean that a single message would not contain a single log but accumulated lines of logs.

**Comment by bradylove** [comment]
Hi @samu,

As mentioned in #56 the RLP Gateway sends envelopes in batches. However you do not have any control at what interval the batches are sent or the number of envelopes in a batch.

If the number of SSE events sent from the RLP Gateway are still frequent, you may want to consider looking at the new [log-cache](https://github.com/cloudfoundry/log-cache-release) component which has a [HTTP GET endpoint](https://github.com/cloudfoundry/log-cache/tree/master#get-apiv1readsource-id) (non-streaming) to read logs and metrics from rather than stream. This would allow you to request logs and/or metrics at your own desired rate and set a limit on the number of envelopes returned per request.
