### ISSUE TITLE
fake RLP server

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/loggregator#61]
I am now use go-loggregator to stream logs from loggregator. And I need a fake loggregator server to support my unit test. Is there an existed fake server?

**Comment by bradylove** [comment]
Hi @qibobo,

Sorry for the delayed response due to the holidays. We do not provide a fake server to be used by external external tests. For a basic example of how we test integrating with the V2 logs server (RLP) you can look at the stub we are using for a test in our [RLP Gateway](https://github.com/cloudfoundry/loggregator/blob/master/rlp-gateway/app/gateway_test.go#L221-L269).

**Comment by qibobo** [comment]
@bradylove thank you.
